# action.yml
name: 'Run-Tests'
description: 'Run MongoDB jstests against a mongo server'
inputs:
  connString:
    description: 'Connection string to Mongo vCore account'
    default: '<empty>'
    required: true
    type: string
  version:
    description: 'Version of the MongoDB jstests to run'
    default: '6.0'
    required: false
    type: string

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.connString }} ${{ inputs.version }}
