# This is a basic workflow that is manually triggered
name: "runtests-mongovcore"

on:
  workflow_dispatch:
    inputs:
      connString:
        description: 'Connection string to Mongo vCore account'
        default: '<empty>'
        required: true
        type: string
      version:
        description: 'Version of the MongoDB jstests to run'
        default: '6.0'
        required: false
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Run docker tests
        uses: ./post-5.0/action.yml
